"""

initial; queue added, trial 1

NOT IGNORED IN VERSION CONTROL
    Contains manul modification

Revision ID: 017e354185f5
Revises: None
Create Date: 2016-04-11 19:23:19.760843

Franklin Chou

"""

# revision identifiers, used by Alembic.
revision = '017e354185f5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # BEGIN: Manually adjusted Alembic commands. #

    op.create_table('tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.Column('status', sa.Integer(), nullable=False),
        sa.Column('forced', sa.Boolean(), nullable=True),
        sa.Column('date_started', sa.DateTime(), nullable=True),
        sa.Column('date_complete', sa.DateTime(), nullable=True),
        # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=64), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('la_username', sa.String(length=64), nullable=True),
        sa.Column('la_password_encrypted', sa.String(length=512), nullable=True),
        sa.Column('confirmed', sa.Boolean(), nullable=True),
        sa.Column('last_run', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('la_username')
    )

    # Once the `tasks` and `users` tables have been completed,
    #   create the `tasks -> user.user_id` foreign key relationship.

    ADD_FOREIGN_KEY_TO_TASKS = '''
        ALTER TABLE tasks
            ADD CONSTRAINT tasks_user_id_FK
            FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
    '''
    op.execute(ADD_FOREIGN_KEY_TO_TASKS)

    op.create_index('idx_task_user_id', 'tasks', ['user_id'], unique=False)

    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_task_user_id', table_name='tasks')
    op.drop_table('tasks')
    ### end Alembic commands ###
