"""
REMOVED 2-WAY ENCRYPTION SCHEMA FOR LEXIS PASSWORDS
FEATURE ABANDONED

Revision ID: 24a7539c562c
Revises: 58eac835a21d
Create Date: 2016-08-06 19:58:58.151894

"""

# revision identifiers, used by Alembic.
revision = '24a7539c562c'
down_revision = '58eac835a21d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('la_password', sa.String(length=128), nullable=True))
    op.drop_column('users', 'la_password_encrypted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('la_password_encrypted', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('users', 'la_password')
    ### end Alembic commands ###
