"""initial; queue added, trial 2

Revision ID: 58eac835a21d
Revises: 017e354185f5
Create Date: 2016-04-11 20:27:26.348011

"""

# revision identifiers, used by Alembic.
revision = '58eac835a21d'
down_revision = '017e354185f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_task_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'task_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_task_id_fkey', 'users', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###
